# Generated by Django 5.2.4 on 2025-10-13 10:04

import django.db.models.deletion
import users.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(help_text='Phone number to send SMS to', max_length=15)),
                ('code', models.CharField(help_text='6-digit OTP code', max_length=6)),
                ('purpose', models.CharField(choices=[('login', 'Login'), ('register', 'Register'), ('password_reset', 'Password Reset'), ('phone_verification', 'Phone Verification')], default='login', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(default=users.models.get_default_expires_at)),
                ('is_used', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='otps', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'OTP',
                'verbose_name_plural': 'OTPs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SMSDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The human-readable name of this device.', max_length=64)),
                ('confirmed', models.BooleanField(default=True, help_text='Is this device ready for use?')),
                ('phone_number', models.CharField(help_text='Phone number to send SMS to', max_length=15, unique=True)),
                ('current_token', models.CharField(blank=True, max_length=255, null=True)),
                ('token_timestamp', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(help_text='The user that this device belongs to.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'SMS Device',
                'verbose_name_plural': 'SMS Devices',
            },
        ),
    ]
