# Generated by Django 5.2.4 on 2025-07-11 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('Admin', 'admin'), ('User', 'user'), ('Treasure', 'treasure')], default='user', max_length=10),
        ),
    ]
