# Generated by Django 5.2.4 on 2025-10-13 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_otp_smsdevice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smsdevice',
            name='current_token',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
