# Generated by Django 5.2.4 on 2025-10-13 12:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_otp_smsdevice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smsdevice',
            name='current_token',
            field=models.CharField(blank=True, default=datetime.datetime(2025, 10, 13, 12, 27, 31, 345748, tzinfo=datetime.timezone.utc), max_length=255),
            preserve_default=False,
        ),
    ]
