"""
Phased Migration for OTP Code Hashing:

This migration initiates the transition from storing plaintext OTP codes to hashed versions for enhanced security.

Phased Approach:
- Phase 1: Introduce optional 'hashed_code' field and mark 'code' as deprecated (this migration: 0004).
- Phase 2: Migrate existing data by hashing codes and populating 'hashed_code', clearing plaintext 'code' (0005_migrate_otp_codes_to_hashed.py).
- Phase 3: Make 'hashed_code' required and non-nullable (TODO: Create migration 0006_alter_otp_hashed_code.py to set null=False).
- Phase 4: Remove the legacy 'code' field entirely (TODO: Create migration 0007_remove_otp_code.py).

Expected Coexistence Timeline:
- Phases 1-2: Deploy immediately in sequence.
- Phase 3: After data migration verification, ideally within 1-2 deployment cycles (e.g., 1 week).
- Phase 4: After a monitoring period (e.g., 1 month) to ensure no dependencies on 'code', and all records use 'hashed_code'.

Rollback Steps:
- Phase 1: Reverse this migration to drop 'hashed_code'.
- Phase 2: Irreversible due to plaintext clearance; manual data restoration from backups would be required if rollback is needed.
- Phase 3: Reverse by allowing nulls in 'hashed_code'.
- Phase 4: Reverse by re-adding 'code' field, but data would need manual repopulation.

Application Changes Note:
During the transition period (Phases 1-3), update application logic to:
- Prefer reading and verifying against 'hashed_code' if present.
- Fall back to direct comparison with 'code' if 'hashed_code' is not set.
- When generating new OTPs: Populate 'hashed_code' with the hashed value; temporarily set 'code' for backward compatibility until Phase 3.
- After Phase 3, exclusively use 'hashed_code' and remove all references to 'code'.

TODO: 
- Create issue/ticket for Phase 3 migration (0006).
- Create issue/ticket for Phase 4 migration (0007).
- Update relevant model methods, views, and utils (e.g., in users/models.py, users/utils.py) to handle dual-field logic during transition.
"""
# Generated by Django 5.2.4 on 2025-10-13 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_smsdevice_current_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='otp',
            name='hashed_code',
            field=models.CharField(blank=True, help_text='Hashed OTP code', max_length=255),
        ),
        migrations.AlterField(
            model_name='otp',
            name='code',
            field=models.CharField(blank=True, help_text='6-digit OTP code (deprecated; use hashed_code)', max_length=6),
        ),
    ]
