# Generated by Django 5.2.4 on 2025-10-13 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_smsdevice_current_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='otp',
            name='hashed_code',
            field=models.CharField(blank=True, help_text='Hashed OTP code', max_length=255),
        ),
        migrations.AlterField(
            model_name='otp',
            name='code',
            field=models.CharField(blank=True, help_text='6-digit OTP code (deprecated; use hashed_code)', max_length=6),
        ),
    ]
