# Generated by Django 5.2.4 on 2025-10-13 17:53

from django.db import migrations
from django.contrib.auth.hashers import make_password

def backfill_hashed_code(apps, schema_editor):
    OTP = apps.get_model('users', 'OTP')
    for otp in OTP.objects.all():
        if otp.code and not otp.hashed_code:
            otp.hashed_code = make_password(otp.code)
            otp.save()

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_otp_hashed_code_alter_otp_code'),
    ]

    operations = [
        migrations.RunPython(backfill_hashed_code),
    ]