# Generated by Django 5.2.4 on 2025-10-13 19:21

from django.db import migrations
from django.contrib.auth.hashers import make_password
from django.core.exceptions import ValidationError
from itertools import islice

def migrate_otp_codes(apps, schema_editor):
    OTP = apps.get_model('users', 'OTP')
    batch_size = 1000
    otps = OTP.objects.filter(code__isnull=False, code__gt='').order_by('id').iterator()
    
    while True:
        batch = list(islice(otps, batch_size))
        if not batch:
            break
        for otp in batch:
            try:
                otp.hashed_code = make_password(otp.code)
                otp.code = ''
                otp.save(update_fields=['hashed_code', 'code'])
            except ValidationError:
                pass  # Skip invalid

def reverse_migrate_otp_codes(apps, schema_editor):
    raise migrations.exceptions.IrreversibleError("This migration cannot be reversed as plaintext codes were cleared.")

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_otp_hashed_code_alter_otp_code'),
    ]

    operations = [
        migrations.RunPython(migrate_otp_codes, reverse_migrate_otp_codes),
    ]