# Generated by Django 5.2.4 on 2025-10-13 17:54

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_data_backfill_hashed_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='hashed_code',
            field=models.CharField(help_text='Hashed OTP code', max_length=255),
        ),
    ]