# Generated by Django 5.2.4 on 2025-10-13 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_migrate_otp_codes_to_hashed'),
        ('users', '0006_alter_otp_hashed_code'),
    ]

    operations = [
    ]
