# Generated by Django 5.2.4 on 2024-10-13 20:00

from django.db import migrations, models

def populate_phones(apps, schema_editor):
    User = apps.get_model('users', 'User')
    for user in User.objects.filter(phone__isnull=True):
        # Generate a unique placeholder phone, e.g., 'temp_' + str(user.id).zfill(9)
        # This ensures uniqueness and fits within max_length=15
        placeholder = f'temp_{str(user.id).zfill(9)}'
        user.phone = placeholder[:15]  # Truncate if necessary
        user.save()

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_merge_20251013_2302'),
    ]

    operations = [
        migrations.RunPython(populate_phones),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=15, unique=True, null=False, blank=False),
        ),
    ]