# Generated by Django 5.2.4 on 2025-10-13 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_populate_and_make_phone_non_nullable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otp',
            name='code',
        ),
        migrations.AlterField(
            model_name='otp',
            name='hashed_code',
            field=models.CharField(blank=True, help_text='Hashed OTP code', max_length=255),
        ),
    ]
