# Generated by Django 5.2.4 on 2025-10-13 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_remove_otp_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='otp',
            name='max_attempts',
            field=models.PositiveIntegerField(default=3),
        ),
        migrations.AddField(
            model_name='otp',
            name='verification_attempts',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name='otp',
            index=models.Index(fields=['phone', 'is_used', 'expires_at'], name='users_otp_phone_c8c281_idx'),
        ),
    ]
