# Generated by Django 5.2.4 on 2025-10-13 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_add_otp_rate_limiting_and_indexing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smsdevice',
            name='current_token',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
