# Generated by Django 5.2.4 on 2025-10-13 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_add_otp_indexes'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='otp',
            constraint=models.UniqueConstraint(condition=models.Q(('is_used', False)), fields=('phone', 'purpose'), name='unique_active_otp_per_phone_purpose'),
        ),
    ]
