# Generated by Django 5.2.4 on 2025-10-14 18:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_add_phone_validators'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smsdevice',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sms_devices', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='otp',
            index=models.Index(fields=['phone', 'purpose', 'is_used'], name='users_otp_phone_86cf13_idx'),
        ),
        migrations.AddIndex(
            model_name='otp',
            index=models.Index(fields=['phone', 'purpose', 'expires_at'], name='users_otp_phone_aa8b93_idx'),
        ),
    ]
