# Generated by Django 5.2.4 on 2025-10-14 19:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_smsdevice_user_otp_users_otp_phone_86cf13_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smsdevice',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sms_devices', to=settings.AUTH_USER_MODEL),
        ),
    ]
