# Generated by Django 5.2.4 on 2025-10-15 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_alter_smsdevice_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smsdevice',
            name='current_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
