# Generated by Django 5.2.4 on 2025-11-06 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_alter_smsdevice_current_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='avatars/default-avatar.png', null=True, upload_to='avatars/'),
        ),
    ]
