# Generated by Django 5.2.4 on 2025-07-30 10:16

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chama', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContributionSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('due_date', models.DateField()),
                ('expected_amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chama', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='chama.chama')),
            ],
            options={
                'db_table': 'contribution_schedule',
            },
        ),
        migrations.CreateModel(
            name='Contribution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('method', models.CharField(choices=[('MPESA', 'M-Pesa'), ('BANK', 'Bank Transfer'), ('CASH', 'Cash')], default='CASH', max_length=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10)),
                ('reference', models.CharField(blank=True, max_length=100, unique=True)),
                ('transaction_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributions', to='chama.membership')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributions', to='contributions.contributionschedule')),
            ],
            options={
                'db_table': 'contribution',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='contributionschedule',
            index=models.Index(fields=['chama', 'due_date'], name='contributio_chama_i_eeb28b_idx'),
        ),
        migrations.AddIndex(
            model_name='contributionschedule',
            index=models.Index(fields=['due_date'], name='contributio_due_dat_143398_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='contributionschedule',
            unique_together={('chama', 'due_date')},
        ),
        migrations.AddIndex(
            model_name='contribution',
            index=models.Index(fields=['schedule', 'transaction_date'], name='contributio_schedul_e751f2_idx'),
        ),
        migrations.AddIndex(
            model_name='contribution',
            index=models.Index(fields=['member', 'transaction_date'], name='contributio_member__615f1e_idx'),
        ),
    ]
