# Generated by Django 5.2.4 on 2025-07-25 09:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chama', '0002_initial'),
        ('contributions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributions_activity_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contribution',
            name='chama',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributions', to='chama.chama'),
        ),
        migrations.AddField(
            model_name='contribution',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributions', to='chama.membership'),
        ),
        migrations.AddField(
            model_name='contribution',
            name='recorded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_contributions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contributioncycle',
            name='chama',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contribution_cycles', to='chama.chama'),
        ),
        migrations.AddField(
            model_name='contribution',
            name='contribution_cycle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contributions', to='contributions.contributioncycle'),
        ),
        migrations.AddField(
            model_name='contributionschedule',
            name='chama',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contribution_schedules', to='chama.chama'),
        ),
        migrations.AddField(
            model_name='contribution',
            name='schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributions', to='contributions.contributionschedule'),
        ),
        migrations.AddIndex(
            model_name='contributioncycle',
            index=models.Index(fields=['chama', 'start_date'], name='contributio_chama_i_cad025_idx'),
        ),
        migrations.AddIndex(
            model_name='contributioncycle',
            index=models.Index(fields=['is_completed'], name='contributio_is_comp_f1e777_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='contributioncycle',
            unique_together={('chama', 'cycle_number')},
        ),
        migrations.AddIndex(
            model_name='contributionschedule',
            index=models.Index(fields=['due_date', 'status'], name='contributio_due_dat_576d50_idx'),
        ),
        migrations.AddIndex(
            model_name='contributionschedule',
            index=models.Index(fields=['chama', 'due_date'], name='contributio_chama_i_eeb28b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='contributionschedule',
            unique_together={('chama', 'due_date')},
        ),
        migrations.AddIndex(
            model_name='contribution',
            index=models.Index(fields=['chama', 'transaction_date'], name='contributio_chama_i_4669b3_idx'),
        ),
        migrations.AddIndex(
            model_name='contribution',
            index=models.Index(fields=['member', 'transaction_date'], name='contributio_member__615f1e_idx'),
        ),
    ]
