# Generated by Django 5.2.4 on 2025-07-25 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contributions', '0002_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ActivityLog',
        ),
    ]
