# Generated by Django 5.2.4 on 2025-07-18 07:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
import uuid


def migrate_contribution_data(apps, schema_editor):
    """
    Migrate existing contribution data to work with the new structure.
    For each existing contribution, create a corresponding membership and schedule.
    """
    Contribution = apps.get_model('contributions', 'Contribution')
    ContributionSchedule = apps.get_model('contributions', 'ContributionSchedule')
    Membership = apps.get_model('chama', 'Membership')
    
    # First, handle any existing contribution schedules that have users
    existing_schedules = ContributionSchedule.objects.all()
    for schedule in existing_schedules:
        # If the schedule has a user, we need to create a proper schedule for the chama
        if hasattr(schedule, 'user') and schedule.user:
            # Create a new schedule for the chama without the user
            new_schedule = ContributionSchedule.objects.create(
                chama=schedule.chama,
                due_date=schedule.due_date,
                expected_amount=schedule.expected_amount,
                status=schedule.status,
            )
            # Update any contributions that reference this schedule
            Contribution.objects.filter(schedule=schedule).update(schedule=new_schedule)
            # Delete the old schedule
            schedule.delete()
    
    # Now handle contributions that have users but no members
    contributions = Contribution.objects.filter(member__isnull=True)
    
    for contribution in contributions:
        if hasattr(contribution, 'user') and contribution.user:
            # Find or create membership for this user in this chama
            try:
                membership = Membership.objects.get(
                    user=contribution.user,
                    chama=contribution.chama
                )
            except Membership.DoesNotExist:
                # Create a membership if it doesn't exist
                membership = Membership.objects.create(
                    user=contribution.user,
                    chama=contribution.chama,
                    role='member',
                    status='active'
                )
            
            # Update the contribution to use the membership
            contribution.member = membership
            
            # Create a schedule if one doesn't exist
            if not contribution.schedule:
                schedule = ContributionSchedule.objects.create(
                    chama=contribution.chama,
                    due_date=contribution.transaction_date.date(),
                    expected_amount=contribution.amount,
                    status='COMPLETED'
                )
                contribution.schedule = schedule
            
            contribution.save()


def reverse_migrate_contribution_data(apps, schema_editor):
    """
    Reverse migration - not implemented as this is a one-way migration
    """
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('chama', '0002_chama_balance'),
        ('contributions', '0002_contribution_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # First, remove the old indexes and constraints
        migrations.RemoveIndex(
            model_name='contribution',
            name='contributio_user_id_f89cfb_idx',
        ),
        migrations.AlterUniqueTogether(
            name='contribution',
            unique_together=set(),
        ),
        
        # Remove the computed fields from ContributionCycle
        migrations.RemoveField(
            model_name='contributioncycle',
            name='collected_total',
        ),
        migrations.RemoveField(
            model_name='contributioncycle',
            name='expected_total',
        ),
        
        # Update ContributionSchedule unique constraint
        migrations.AlterUniqueTogether(
            name='contributionschedule',
            unique_together={('chama', 'due_date')},
        ),
        
        # Add the new fields to Contribution
        migrations.AddField(
            model_name='contribution',
            name='contribution_cycle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contributions', to='contributions.contributioncycle'),
        ),
        migrations.AddField(
            model_name='contribution',
            name='member',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contributions', to='chama.membership'),
        ),
        
        # Make schedule nullable temporarily
        migrations.AlterField(
            model_name='contribution',
            name='schedule',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contributions', to='contributions.contributionschedule'),
        ),
        
        # Run the data migration
        migrations.RunPython(migrate_contribution_data, reverse_migrate_contribution_data),
        
        # Add the new index
        migrations.AddIndex(
            model_name='contribution',
            index=models.Index(fields=['member', 'transaction_date'], name='contributio_member__615f1e_idx'),
        ),
        
        # Remove the old user fields
        migrations.RemoveField(
            model_name='contribution',
            name='user',
        ),
        migrations.RemoveField(
            model_name='contributionschedule',
            name='user',
        ),
    ]
