# Generated by Django 5.2.4 on 2025-07-21 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contributions', '0003_update_contribution_models'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contribution',
            name='confirmed_at',
        ),
        migrations.RemoveField(
            model_name='contribution',
            name='is_confirmed',
        ),
        migrations.AlterField(
            model_name='contribution',
            name='method',
            field=models.CharField(choices=[('MPESA', 'M-Pesa'), ('BANK', 'Bank Transfer'), ('CASH', 'Cash')], default='MPESA', max_length=10),
        ),
        migrations.AlterField(
            model_name='contribution',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('DECLINED', 'Declined')], default='PENDING', max_length=10),
        ),
    ]
