# Generated by Django 5.2.4 on 2025-07-21 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contributions', '0004_remove_contribution_confirmed_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contributionschedule',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('DECLINED', 'Declined')], default='PENDING', max_length=10),
        ),
    ]
