# Generated by Django 5.2.4 on 2025-07-27 14:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chama',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the Chama', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('currency', models.CharField(max_length=10)),
                ('minimum_members', models.IntegerField(default=1)),
                ('maximum_members', models.IntegerField()),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('join_code', models.CharField(blank=True, default='', help_text='Auto-generated code for users to join', max_length=12, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the membership record', primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('member', 'Member'), ('admin', 'Admin'), ('treasurer', 'Treasurer')], default='member', max_length=20)),
                ('status', models.CharField(choices=[('invited', 'Invited'), ('pending', 'Pending'), ('active', 'Active'), ('removed', 'Removed')], default='pending', max_length=20)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('payout_order', models.IntegerField(blank=True, null=True)),
                ('chama', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='chama.chama')),
            ],
        ),
    ]
