# Generated by Django 5.2.4 on 2025-07-27 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chama', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chama',
            name='balance',
        ),
    ]
