# Generated by Django 5.2.4 on 2025-07-25 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chama', '0002_chama_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='status',
            field=models.CharField(choices=[('invited', 'Invited'), ('pending', 'Pending'), ('active', 'Active'), ('removed', 'Removed')], default='pending', max_length=20),
        ),
    ]
