# Generated by Django 5.2.4 on 2025-07-27 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chama', '0002_chama_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='chama',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
