# Generated by Django 5.2.4 on 2025-07-26 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chama', '0002_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContributionSchedule',
        ),
    ]
