# Generated by Django 5.2.4 on 2025-07-26 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chama', '0003_delete_contributionschedule'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='chama',
            constraint=models.UniqueConstraint(fields=('name',), name='unique_chama_name'),
        ),
    ]
