# Generated by Django 5.2.4 on 2025-07-29 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chama', '0003_alter_membership_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chama',
            name='contribution_amount',
        ),
        migrations.RemoveField(
            model_name='chama',
            name='contribution_day',
        ),
        migrations.RemoveField(
            model_name='chama',
            name='contribution_frequency',
        ),
        migrations.RemoveField(
            model_name='chama',
            name='late_payment_fee',
        ),
    ]
