# Generated by Django 5.2.4 on 2025-08-01 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chama', '0002_initial'),
        ('chama', '0004_remove_chama_contribution_amount_and_more'),
    ]

    operations = [
    ]
