# Generated by Django 5.2.4 on 2025-08-08 07:01

import chama.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chama', '0004_remove_chama_contribution_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chama',
            name='join_code',
            field=models.CharField(blank=True, default=chama.models.generate_unique_code, max_length=12, unique=True),
        ),
    ]
