# Generated by Django 5.2.4 on 2025-08-04 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chama', '0004_remove_chama_contribution_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chama',
            name='contribution_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='chama',
            name='contribution_day',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chama',
            name='contribution_frequency',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chama',
            name='late_payment_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
