# Generated by Django 5.2.4 on 2025-07-21 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chama', '0004_remove_chama_is_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='chama',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
