# Generated by Django 5.2.4 on 2025-07-21 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chama', '0005_chama_is_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chama',
            name='is_admin',
        ),
    ]
