# Generated by Django 5.2.4 on 2025-08-10 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chama', '0005_alter_chama_join_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chama',
            name='join_code',
            field=models.CharField(max_length=12, unique=True),
        ),
    ]
