# Generated by Django 5.2.4 on 2025-08-09 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chama', '0005_chama_contribution_amount_chama_contribution_day_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chama',
            name='contribution_amount',
        ),
        migrations.RemoveField(
            model_name='chama',
            name='contribution_day',
        ),
        migrations.RemoveField(
            model_name='chama',
            name='contribution_frequency',
        ),
        migrations.RemoveField(
            model_name='chama',
            name='late_payment_fee',
        ),
    ]
