# Generated by Django 5.2.4 on 2025-08-10 14:39

import chama.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chama', '0006_alter_chama_join_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chama',
            name='join_code',
            field=models.CharField(blank=True, default=chama.models.generate_unique_code, editable=False, max_length=12, unique=True),
        ),
    ]
