# Generated by Django 5.2.4 on 2025-07-30 10:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activity', '0001_initial'),
        ('chama', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylog',
            name='chama',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_activity_logs', to='chama.chama'),
        ),
    ]
