# Generated by Django 5.2.4 on 2025-07-25 11:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylog',
            name='action',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
