# Generated by Django 5.2.4 on 2025-07-25 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0004_activitylog_action'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activitylog',
            name='action',
        ),
    ]
