# Generated by Django 5.2.4 on 2025-07-13 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('sw', 'Swahili')], default='en', max_length=5),
        ),
    ]
